系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/loginfunction/urls.py
# 这是老版本的导入方式，新版本的方式不用URL，用path
from django.conf.urls import include,url
from loginfunction import views

urlpatterns = [
    url('^login/?$',views.login),
    url('^ajax_login$',views.ajax_login),
    url('^index$',views.index,name='index'),

    url('^set_cookie$',views.set_cookie), # 这个是设置cookie的值
    url('^get_cookie$',views.get_cookie), # 这里是得到 cookie的值
    url('^set_session$',views.set_session), # 这个是设置session的值
    url('^get_session$',views.get_session), # 这里是得到 session的值

    url('^templateLanguageBase$',views.templateLanguageBase), # 模板语言基础用法

    url('^child$',views.child_template), # 模板继承使用
    url('^excape$',views.excape),  # 转义的使用

    url('^url_reverse$',views.url_reverse),  # url 的反向解析

    url('^url_reverse_args/(\d+)/(\d+)$',views.url_reverse_args,name='url_reverse_args'),

    url('^url_reverse_argsname/(?P<a>\d+)/(?P<b>\d+)$', views.url_reverse_argsname, name='url_reverse_argsname'),

    url('^get_authcode$',views.get_authcode),

    url('^show_authcode$',views.show_authcode),  # 显示验证码

    url('^test_view_redirect$',views.test_view_redirect),  # 测试视图反向解析

    url('^show_args/(\d+)/(\d+)$',views.show_args,name='show_args'),  # 测试带参数的反向解析

    url('^show_kwargs/(?P<c>\d+)/(?P<d>\d+)$', views.show_kwargs,name='show_kwargs'),  # 测试带参数的反向解析

    url('^static_file_image$',views.static_file_image),  # 这个是静态文件使用图片

    url('^get_computer_ip$',views.get_computer_ip),  # 获取电脑的ip地址

    url('^refuse_ip$',views.refuse_ip),  # 拒绝某一个ip的请求

    url('^middleware_exe$',views.middleware_exe),  # 中间件函数的执行

    url('^pic_upload$',views.pic_upload),  # 图片上传界面

    url('^upload_handle$',views.upload_handle),  # 图片上传处理函数

    url('^paging_use/(?P<index>\d*)$',views.paging_use),  # 分页数据显示

    url('^area_select$',views.area_select),  # 地区选择

    url('^province$',views.province),   # 这个是省的数据

    url('^city/(?P<area_id>\d+)',views.city),  # 这个是城市的数据

]

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/project3/urls.py
from django.contrib import admin
from django.urls import path
# 这是老版本的导入方式，新版本的方式不用URL，用path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^',include(('loginfunction.urls','loginfunction'),namespace='loginfunction'))
]

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/loginfunction/models.py
from django.db import models

class UserInfo(models.Model):
    """用户信息表模型"""
    username = models.CharField(max_length=20);
    password = models.CharField(max_length=20);
    gender   = models.BooleanField(verbose_name='性别',default=False);

    def __str__(self):
        return self.username;

    def title(self):
        """这个方法可以用来计算"""
        return self.username;
    title.admin_order_field = 'username';
    title.short_description = '姓名'


    class Meta:
        db_table = "userinfo";  # 这个是指定用户信息表的名字


class TestPic(models.Model):
    """图片上传模型"""
    pic = models.ImageField(upload_to='loginfunction');


class AreaData(models.Model):
    """地理模型"""
    # area id
    area_id = models.CharField(max_length=20);

    # title
    area_title = models.CharField(max_length=20);

    # parent id
    parent_id = models.CharField(max_length=20);

    class Meta:
        db_table = "area_data";

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/loginfunction/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect

from loginfunction.models import UserInfo
from loginfunction.publicLibrary import public_pac

from django.conf import settings
from loginfunction.models import TestPic
from loginfunction.models import AreaData

import sys


# Create your views here.

def login(request):
    """这里是登录视图响应方法"""

    if request.session.has_key('isLogin'):  # 如果存在就返回首页
        return HttpResponseRedirect('/index');
    else:
        username = request.COOKIES.get("username");
        if username:
            return render(request, 'loginfunction/login.html', {"username": username})
    return render(request, 'loginfunction/login.html');


def ajax_login(request):
    """这个是 ajax 请求登录"""
    # 1.获取请求的参数据
    if request.method == 'GET':
        username = request.GET.get('username');
        password = request.GET.get('password');
        checkbox_select = request.GET.get('checkbox_select');
    elif request.method == 'POST':
        username = request.POST.get('username');
        password = request.POST.get('password');
        checkbox_select = request.POST.get('checkbox_select');
    else:
        username = None;

    # request.GET/POST  返回的数据是 QueryDict 类型
    # from django.http.request import QueryDict

    print('hello');
    # 2.数据库数据校验，是否对
    temp = UserInfo.objects.filter(username=username);
    if temp:
        if temp[0].password == password:
            # 校验成功之后需要存储记住账号
            response = JsonResponse({'res': 1});
            if checkbox_select == 'on':  # 这个表示要记住账号，只有登录成功的时候才需要记录账号
                response.set_cookie('username', username);
            # 登录成功之后我们需要保存登录状态，我们需要用session 来保存登录状态
            request.session["isLogin"] = 1;
            return response;  # 这个用户校验成功
        else:
            return JsonResponse({'res': 0});  # 这是个用户密码错误
    else:
        return JsonResponse({'res': 2});  # 这个是用户不存在


def index(request):
    funcName = sys._getframe().f_code.co_name  # 获取调用函数名
    lineNumber = sys._getframe().f_back.f_lineno  # 获取行号
    print(lineNumber, funcName)
    return render(request, 'loginfunction/index.html');


def set_cookie(request):
    """设置cookie信息"""
    response = HttpResponse("设置cookie信息");
    # cookie 的键为：num 值为1
    response.set_cookie('num', 1);
    return response;


def get_cookie(request):
    """获取cookie值"""
    # 取出cookie信息
    cookie_value = request.COOKIES["num"];
    return HttpResponse(cookie_value);


def set_session(request):
    """设置session 的值"""
    request.session['username'] = 'fan';
    request.session['age'] = 18;
    return HttpResponse("设置session信息");


def get_session(request):
    """得到session信息"""
    username = request.session["username"];
    age = request.session["age"];

    return HttpResponse("得到session的值" + username + str(age));


def clear_session(request):
    """清除session"""
    # 清除session 中部分键值
    del request.session["age"];
    # 清除所有的session 在存储中删除部分
    request.session.clear()
    # 清除所有的session 在存储中也全部删除
    request.session.flush()

    return HttpResponse('清除成功');


def templateLanguageBase(request):
    """模板语言基础"""

    dict_content = {'title': 'fan', 'age': 18, 'parent': True};
    list_content = ['fan', 'cnn', 'wdk', 'lyx', 'bb'];
    num_list = list(range(0, 10));
    users = UserInfo.objects.all();

    return render(request, 'loginfunction/templateLanguageBase.html', {
        'dict_content': dict_content, 'list_content': list_content, 'users': users,
        'num_list': num_list
    });


def child_template(request):
    """模板继承的使用"""
    return render(request, 'loginfunction/child.html');


def excape(request):
    """转义"""
    return render(request, 'loginfunction/excape.html', {
        'content': '<h1>I love you</h1>',
        'content1': '&lth1&gt I am very beautiful &lt/h1&gt'
    })


def url_reverse(request):
    """url 的反向解析"""

    return render(request, 'loginfunction/url_reverse.html');


def url_reverse_args(request, a, b):
    """带参数的反向url 解析"""
    return render(request, 'loginfunction/url_reverse_args.html', {'content': (a, b,)})


def url_reverse_argsname(request, a, b):
    """带参数的反向url 解析"""
    return render(request, 'loginfunction/url_reverse_args.html', {'content': (a, b,)})


def get_authcode(request):
    """获取验证码"""

    # buf_value 这个是验证码图片数据 auth_code 这个是验证码

    buf_value, auth_code = public_pac.get_authcode_picture();

    # 这个是返回给客户端的数据 数据mime类型为png
    return HttpResponse(buf_value, 'image/png');


def show_authcode(request):
    """返回验证码"""
    return render(request, 'loginfunction/show_authcode.html');


from django.urls import reverse


def test_view_redirect(request):
    """测试视图的反向解析"""
    # 重定向到 redirect('/index');
    url = reverse('loginfunction:index');

    # 重定向到/show_args/1/2
    url = reverse('loginfunction:show_args', args=(1, 2));

    # 重定向到/show_kwargs/3/4
    url = reverse('loginfunction:show_kwargs', kwargs={'c': 3, 'd': 4});

    return redirect(url);


def show_args(request, a, b):
    return render(request, 'loginfunction/url_reverse_args.html', {"content": (a, ':', b)});


def show_kwargs(request, c, d):
    return render(request, 'loginfunction/url_reverse_args.html', {"content": (c, ':', d)});


def static_file_image(request):
    """静态文件的使用"""
    return render(request,'loginfunction/static_file_image.html');

def get_computer_ip(request):
    """获取电脑的ip"""
    user_ip = request.META['REMOTE_ADDR'];

    return HttpResponse(user_ip);

def refuse_ip(request):
    """拒绝某一个ip的访问"""
    # 这个是要拒绝的ip地址list
    REFUSE_IPS = ['192.168.1.23'];

    # 获取访问的ip
    user_ip = request.META["REMOTE_ADDR"];

    if user_ip in REFUSE_IPS:
        return HttpResponse("你的ip被我们禁止了");

    return HttpResponse("正常访问");

def block_ip(view_func):

    def wrapper(request,*args,**kwargs):
        # 获取访问的ip
        user_ip = request.META["REMOTE_ADDR"];
        REFUSE_IPS = ['192.168.1.23'];
        if user_ip in REFUSE_IPS:
            return HttpResponse("你的ip被我们禁止了");
        else:
            return view_func(request,*args,**kwargs);

    return wrapper;


def middleware_exe(request):

    rep = HttpResponse('I am very well');

    def render():
        print('index ｂｅｆｏｒｅ')
        return HttpResponse('index');

    #  对象属性
    rep.render = render;

    return rep;

    return

# /pic_upload
def pic_upload(request):
    """这个是图片上传界面"""
    return render(request,'loginfunction/pic_upload.html');

# /upload_handle
def upload_handle(request):
    """图片上传处理函数"""
    # 1.get file upload object
    pic = request.FILES['pic'];

    # 2.create a file
    save_path = '%s/loginfunction/%s' % (settings.MEDIA_ROOT,pic.name);

    # 3.get upload file content and write new create file
    with open(save_path,'wb+') as f:
        for content in pic.chunks():
            f.write(content);


    # 4.save record in database
    TestPic.objects.create(pic='loginfunction/%s'%pic.name);
    # 5.return
    return HttpResponse("upload picture ok!");

from django.core.paginator import Paginator
def paging_use(reqeust,index):
    """分页"""
    # １．get data
    data = UserInfo.objects.all();

    # 2. every paging show ten
    paginator = Paginator(data,10);

    # 3.get paging data
    if not index:
        index = 1;
    pag = paginator.page(int(index));

    return render(reqeust,'loginfunction/paging_use.html',{"pag":pag})

def area_select(request):
    """城市选择器"""

    return render(request,'loginfunction/area_select.html')

def province(request):
    """查询省的数据"""
    # 1.查询数据
    province = AreaData.objects.filter(parent_id='0')

    # 2.构建JSON 数据
    area_list = [];

    for area in province:
        area_list.append((area.area_id,area.area_title));

    # 3.返回数据
    return JsonResponse({'data':area_list});

# /city/(\d+)
def city(request,area_id):
    """This is city' data"""

    # 1.query data
    area_data = AreaData.objects.filter(parent_id=area_id);

    # 2.make json data
    area_list = [];
    for area in area_data:
        area_list.append((area.area_id,area.area_title));

    # 3.return json data
    return JsonResponse({'data':area_list});

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/area_select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>城市选择器</title>
    <script src="/static/js/jquery-3.4.1.js"></script>
    <script>
        $(function () {

            $.get('/province',function (data) {

                re = data.data;
                /*
                for (i = 0; i<re.length;i++){
                    area_id = re[i][0];
                    area_title = re[i][1];

                    optionStr = "<option value=" + area_id + ">" + area_title + "</option>"
                    $('#select').append(optionStr);
                }
                 */
                $.each(re,function (index,item) {
                    area_id = item[0];
                    area_title = item[1];

                    optionStr = "<option value=" + area_id + ">" + area_title + "</option>"
                    $('#province').append(optionStr);
                })
            });

            // click option time
            $('#province').change(function () {
                area_id = $(this).val()

                if (area_id == null){
                      //clear last click data
                    $('#city').html('<option value="">--选择城市--</option>');
                    $('#country').html('<option value="">--选择区县--</option>');
                    return;
                }

                //clear last click data
                $('#city').html('<option value="">--选择城市--</option>');
                $('#country').html('<option value="">--选择区县--</option>');

                $.get('/city/' + area_id,function (data) {

                    re = data.data;

                    $.each(re,function (index,item) {
                        area_id = item[0];
                        area_title = item[1];

                        optionStr = "<option value=" + area_id + ">" + area_title + "</option>"
                        $('#city').append(optionStr);
                    })

                });

            });

             // click option time
            $('#city').change(function () {
                area_id = $(this).val()

                if (area_id == null){

                    return;
                }
                //clear last click data
                $('#country').html('<option value="">--选择区县--</option>');
                $.get('/city/' + area_id,function (data) {

                    re = data.data;

                    $.each(re,function (index,item) {
                        area_id = item[0];
                        area_title = item[1];

                        optionStr = "<option value=" + area_id + ">" + area_title + "</option>"
                        $('#country').append(optionStr);
                    })

                });

            });



        });

    </script>
</head>
<body>
<select name="" id="province">
    <option value="">--选择省份--</option>
</select>
<select name="" id="city">
    <option value="">--选择城市--</option>
</select>
<select name="" id="country">
    <option value="">--选择区县--</option>
</select>
</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            我是基类模板的title
        {% endblock %}

    </title>

    <style>
        .header{
            position: absolute;
            left: 0px;
            top: 0px;
            width: 100%;
            height: 40px;
            background-color: lightgreen;
            color: red;
            text-align: center;
            line-height: 40px;
        }

         .bottom{
            position: absolute;
            left: 0px;
            bottom: 0px;
            width: 100%;
            height: 40px;
            background-color: lightgreen;
            color: red;
             text-align: center;
             line-height: 40px;

        }

        .center{
            position: absolute;
            left: 0px;
            top: 40px;
            bottom: 40px;
            right: 0px;
            background-color: aquamarine;
            text-align: center;
        }
    </style>
</head>
<body>
{% block header %}
<div class="header">我是头部</div>
{% endblock %}

{% block content %}
<div class="center">
    {% block content_detail %}
        <h1>内容</h1>
    {% endblock %}
</div>
{% endblock %}

{% block bottom %}
<div class="bottom">我是底部</div>
{% endblock %}
</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/child.html
{% extends 'loginfunction/base.html' %}

{% block title %}
我是孩子的标题
{% endblock %}

{% comment %}
{% block content %}
    {{ block.super }}
{% endblock %}
{% endcomment %}

 {% block content_detail %}
        <h1>child内容</h1>
 {% endblock %}

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/excape.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>使用safe关闭转义</title>
</head>
<body>
html转义：<br>
{{ content }}<br>
使用过滤器safe 来转义 <br>
{{ content|safe }}

使用autoexcape关闭转义 <br>
{% autoescape on %}
{{ content }}
{% endautoescape %}
<br>
使用autoexcape打开转义 <br>
{% autoescape off %}
{{ content }}
{% endautoescape %}

如果是转义字符，默认转义 <br>

{% autoescape off %}
{{ content1 }} <br>
    {{ content }}<br>
{% endautoescape %}

<br>
模板硬编码中，字符串默认不会经过转义：<br>
{{ test|default:'<h1> I love you too</h1>' }} <br>

手动进行转义: <br>
{{ test|default:'&lt;h1&gt; I love you too&lt;/h1&gt;' }} <br>


</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <style>
        h1{
            margin: 50px auto 0px;
        }
    </style>
</head>
<body>

<h1>登录成功</h1>

</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录界面</title>
    <script src="/static/js/jquery-3.4.1.js" charset="utf-8" ></script>

    <script type="text/javascript">
        $(function () {
            $('#login_btn_post').click(function () {

                username = $('#username').val();
                password = $('#password').val();
                checkbox_select = $('#checkbox_select').val();
                $.ajax({
                    'url':'/ajax_login',
                    'dataType':'json',
                    'type':'post',
                    'async':false, //这个是设置同步ajax 请求
                    'data':{'username':username,'password':password,'checkbox_select':checkbox_select},
                    'success':function (data) {
                        console.log(data)
                        if (data.res == 1){
                            location.href = '/index';
                        } else if (data.res == 2){
                            alert('用户名不存在');
                        } else {
                            $('#passwork_error').show();
                        }
                    },
                    'fail':function (error) {
                        console.log(error)
                    }
                });
            });

            $('#login_btn_get').click(function () {

                username = $('#username_get').val();
                password = $('#password_get').val();
                $.ajax({
                    'url':'/ajax_login',
                    'dataType':'json',
                    'type':'get',
                    'async':false, //这个是设置同步ajax 请求
                    'data':{'username':username,'password':password},
                    'success':function (data) {
                        console.log(data)
                        if (data.res == 1){
                            location.href = '/index';
                        } else if (data.res == 2){
                            alert('用户名不存在');
                        } else {
                            $('#passwork_error_get').show();
                        }
                    },
                    'fail':function (error) {
                        console.log(error)
                    }
                });
            });
        });
    </script>

    <style>
        div{
            width: 300px;
            margin: 50px auto 0px;
        }
        input{
            display: block;
            width: 300px;
            margin: 0px;
            padding: 0px;
        }

        #checkbox_select{
            text-align: left;
            width: 40px;
            height: 20px;
            display: inline-block;
        }

        em{
            height: 20px;
        }

        #passwork_error,#passwork_error_get{
            display: none;
            color: red;
        }
    </style>
</head>
<body>

<div>
    <p>用户名：</p>
    <input type="text" id="username" value="{{ username }}">
    <p>密码：</p>
    <input type="text" id="password">
    <p id="passwork_error">密码错误，请重新输入！</p>
    <br>
    <br>
    <input type="checkbox" id="checkbox_select"><em>记住账号</em>
    <input type="button" value="POST登录" id="login_btn_post">
</div>

<div>
    <form action="/login">
        <p>用户名：</p>
        <input type="text" id="username_get" name="username">
        <p>密码：</p>
        <input type="text" id="password_get" name="password">
        <p id="passwork_error_get">密码错误，请重新输入！</p>
        <br>
        <br>
        <input type="button" value="GET登录(如果用表单提交，需要另外写服务器方法)" id="login_btn_get">
    </form>
</div>

</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/paging_use.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>paging use</title>
</head>
<body>

<ul>
    {% for foo in pag %}
        <li>{{ foo }}</li>
    {% empty %}
        <li>empty data</li>
    {% endfor %}
</ul>

{% if pag.has_previous %}
    <a href="/paging_use/{{ pag.previous_page_number}}">上一页</a>
{% endif %}

<div>
    {% for index in pag.paginator.page_range %}

        {% if index == pag.number %}
            <em style="background-color: white">{{ index }}</em>
        {% else %}
            <a href="/paging_use/{{ index }}" style="background-color: red">{{ index }}</a>
        {% endif %}
    {% endfor %}

</div>

{% if pag.has_next %}
    <a href="/paging_use/{{ pag.next_page_number }}">下一页</a>
{% endif %}

</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/pic_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图片上传表单</title>
</head>
<body>

<form action="upload_handle" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="pic"><br>
    <input type="submit" value="上传">
</form>

</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/show_authcode.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>显示验证码</title>

    <style>
        img{
            display: inline-block;
            width: 200px;
            height: 100px;
        }
    </style>
</head>
<body>

<img src="/get_authcode" alt="验证码">

</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/static_file_image.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>静态文件图片的使用</title>

    <style>
        img{
            display: block;
            width: 200px;
            height: 100px;
        }
    </style>
</head>
<body>
{# 这个是绝对路径 #}
<img src="/static/images/beauty.png" alt="">

{# 这个是动态路径 #}
<img src="{% static 'images/beauty.png' %}" alt="">

<img src="/static/images/beauty.png" alt="">

</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/templateLanguageBase.html
{% load extra_tags %}  {# 这个是加载自定义的过滤器 #}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模板语言基础知识</title>
</head>
<body>

<p>for 循环的使用 </p>
{% for foo in list_content %}
    {% if foo == 'fan' %}
        <li style="background-color: red">{{ forloop.counter }}:{{ foo }}</li>
    {% else %}
        <li>{{ forloop.counter }}:{{ foo }}</li>
    {% endif %}
{% endfor %}

<p>if 语句使用</p>

{% if users.0.id == 1 %}
    <li>我是{{ users.0.id }}号：{{ users.0.username }}</li>
{% else %}
{% endif %}

<p>关系运算符的使用</p>
{% if users.0.id > 1 %}
    <li>我是{{ users.0.id }}号：{{ users.0.username }}</li>
{% else %}
    <li style="background-color: red">我是{{ users.0.id }}号：{{ users.0.username }}</li>
{% endif %}

<p>逻辑运算的运用 not and or</p>

{% if  not 1 %}
    <li>我是{{ users.0.id }}号：{{ users.0.username }}</li>
{% else %}
    <li style="background-color: red">我是{{ users.0.id }}号：{{ users.0.username }}</li>
{% endif %}


<p>过滤器defalut的使用</p>

<p style="background-color: bisque">{{ conent|default:'后台没有传值过来' }}</p>

<p>自定义过滤器的使用</p>
{# 只有一个参数的自定义过滤器 #}
{% for num in num_list %}
    {% if num|mod %}
        <li style="background-color: lightgreen">{{ num }}是偶数</li>
    {% else %}
        <li>{{ num }}不是偶数</li>
    {% endif %}
{% endfor %}

{# 只有两个参数的自定义过滤器 #}
{% for num in num_list %}
    {% if num|mod:3 %}
        <li style="background-color: lightgreen">{{ num }}是3倍数</li>
    {% else %}
        <li>{{ num }}不是3的倍数</li>
    {% endif %}
{% endfor %}


</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/url_reverse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>url 反向解析</title>
</head>
<body>

<br>
url反向解析 返回 name=index 的链接url <br>
<a href="{% url 'loginfunction:index' %}">首页index</a>
<br>
url反向解析 返回 name=url_reverse_args 带参数 的链接url <br>
<a href="{% url 'loginfunction:url_reverse_args' 1 2  %}">url_reverse_args/1/2</a> <br>

url反向解析 返回 name=url_reverse_argsname 带参数 的链接url <br>
<a href="{% url 'loginfunction:url_reverse_argsname' a=1 b=2  %}">url_reverse_argsname/1/2</a> <br>

</body>
</html>

系统学习Python/Django/ProjectFolder2/ProjectFolder/project3/project3/templates/loginfunction/url_reverse_args.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>带参数的url 反向解析</title>
</head>
<body>

{{ content }}

</body>
</html>